export const CONFIG = {
  COOKIE_PERSIST_DEBOUNCE_MS: 300,
  HTTP_TIMEOUT_MS: 15000,
  SCHEDULE_CACHE_TTL_MS: 6 * 60 * 60 * 1000,
  SCHEDULE_CACHE_MAX_AGE_MS: 30 * 24 * 60 * 60 * 1000,
  AUTO_REFRESH_INTERVAL_MS: 60 * 60 * 1000,
  AUTO_REFRESH_NEXT_WEEK_MS: 6 * 60 * 60 * 1000,
  NETWORK_STALL_TIMEOUT_MS: 20000,
  COOKIE_REFRESH_INTERVAL_MS: 30 * 60 * 1000,
  ACTIVE_HOURS_START: 6,
  ACTIVE_HOURS_END: 23,
  WINDOW_MIN_HEIGHT: 610,
  WINDOW_MAX_HEIGHT: 610,
  WINDOW_DEFAULT_WIDTH: 800,
  WINDOW_DEFAULT_HEIGHT: 610,
  WINDOW_BLUR_HIDE_DELAY_MS: 150,
  TRAY_SHOW_POSITION_MARGIN: 12,
  SCHEDULE_SHOW_DELAY_MS: 2000,
  APP_NAME: "UNETI Schedule Widget",
  APP_SERVICE_NAME: "uneti-schedule-widget",
  UNETI_DOMAIN: "uneti.edu.vn",
  UNETI_LOGIN_URL: "https://support.uneti.edu.vn/dang-nhap",
  UNETI_API_BASE: "https://apiv3.uneti.edu.vn/api",
  UNETI_SCHEDULE_ENDPOINT: "https://apiv3.uneti.edu.vn/api/SP_TC_SV_KetQuaHocTap_TiepNhan/EDU_Load_Para_MaSinhVien_LichHocSinhVien",
  UNETI_EXAM_ENDPOINT: "https://apiv3.uneti.edu.vn/api/SP_TC_SV_KetQuaHocTap_TiepNhan/EDU_Load_Para_MaSinhVien_LichThiSinhVien",
  UNETI_GRADES_ENDPOINT: "https://apiv3.uneti.edu.vn/api/SP_TC_SV_KetQuaHocTap_TiepNhan/EDU_Load_Para_MaSinhVien_ChiTiet",
  UNETI_GPA_ENDPOINT: "https://apiv3.uneti.edu.vn/api/SP_TC_SV_KetQuaHocTap_TiepNhan/EDU_Load_Para_MaSinhVien_DiemTrungBinhHocKy",
  COOKIE_KEYTAR_SERVICE: "uneti-schedule-app",
  COOKIE_KEYTAR_ACCOUNT: "cookies",
  DB_FILENAME: "schedule.db",
};
